### ISSUE TITLE
gpupdate-setup not work with emtpty profile

### ISSUE THREAD

**Issue by mastersin** [altlinux/gpupdate#101]
There are a problem found during testing new gpupdate with empty profile:
```bash
[root@dc ~]# gpupdate-setup write enable dmnet
dmnet
[root@dc ~]# echo $?
0
[root@dc ~]# gpupdate-setup 
disabled
[root@dc ~]# cat /usr/share/local-policy/dmnet/Machine/Registry.pol.xml 
<?xml version="1.0" encoding="utf-8"?>
<PolFile num_entries="0" signature="PReg" version="1">
</PolFile>
```

Next command runs in setup process:
```
/usr/sbin/control system-policy gpupdate
/usr/sbin/gpoa --nodomain --loglevel 5
systemctl --global enable gpupdate-user.service
```

But status of gpupdate enabled or disabled defines by gpupdate.service enabled (simply by `/etc/systemd/system/multi-user.target.wants/gpupdate.service` exists)

So, if **_nodomain_** bootstrap process not includes **gpupdate.service** enabling, successfully running of all steps of `gpupdate-setup` not enables gpupdate.service as needed. Also every separate step in setup process not checks result in command() method runs from python.

**Comment by NIR-Ginko** [comment]
@mastersin , could you please describe the problem in Russian 'cause I can't understand your English.
