### ISSUE TITLE
Ярлыки на рабочий стол

### ISSUE THREAD

**Issue by ekorneechev** [altlinux/gpupdate#22]
Возможно уже реализовано в shortcut_applier.py, тогда хотелось бы увидеть описание настройки через RSAT.

**Comment by NIR-Ginko** [comment]
It's expected that you'll be configuring shortcuts via standard RSAT facilities. It's also expected that shortcuts that were pre-configured for Windows will be reinterpreted for Linux. I'm also testing URIs at the moment.

**Comment by ekorneechev** [comment]
What about linux-specific program shortcuts (remmina, connector and others)?

**Comment by NIR-Ginko** [comment]
There must be no problem - just write down UNIX-style path as *Target Path*. As for link path - the Windows-style variables must be transformed to UNIX-style paths automatically (but there is some limitations). You may be also interested in reviewing and testing my PR regarding shortcuts pointing to network shares (CIFS/Samba): https://github.com/altlinux/gpupdate/pull/24 .

**Comment by gochankot** [comment]
У меня и на тестовой стажеркой машине с ALT Рабочая станция p9 короче работает так:
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=xdg-open smb://10.*.*.*/SYSVOL/
Name[ru_RU]=SYSVOL Share TEST
Name=SYSVOL Share TEST
```
Не работает и так: (взято из 
 https://github.com/altlinux/gpupdate/blob/a3684e5d0baad13fa2fecd68f09e835c264cb0f4/gpoa/test/files/share.desktop - кстати @NIR-Ginko не пали наши ip адреса внутренние)))
```
[Desktop Entry]
Type=Link
Version=1.0
Name=Docs
GenericName=Link to CIFS disk
Comment=Link to Samba share
URL=smb://10.*.*.*/
```
Не работает вот так:
```
[Desktop Entry]
Type=Application
Version=1.1
Name=Ne Rabotaet SYSVOL Share Link
Terminal=false
GenericName=Link to CIFS share
Comment=Link to Samba share
Exec="xdg-open smb://10.*.*.*/SYSVOL/"
```

но при этом на дефолтной установки есть:
```
[Desktop Entry]
Version=1.0
Type=Application
Exec=xbrowser /usr/share/doc/indexhtml/index.html
StartupNotify=false
Icon=basealt
Name=About system
Categories=System;Documentation;

# Translations
Name[ru]=О системе
```
и ему не требуется
```
#!/usr/bin/env <что_то_например_xbrowser>
``` 
возможно имеет значение параметр
``` 
Terminal=false
```
